# Generated by Django 5.2 on 2026-02-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='default',
            field=models.BooleanField(default=False, verbose_name='¿Rol por defecto?'),
        ),
    ]
